version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: uwsgi --ini docker/app/uwsgi.ini
    volumes:
      - .:/code
      - django-socket:/home/socket
    restart: always
    depends_on:
      - postgres
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/uwsgi_params:/home/uwsgi_params
      - django-socket:/home/socket
      - .:/code
    restart: always
    ports:
      - 8080:8000
    depends_on:
      - app
volumes:
  django-socket:
