# Generated by Django 3.0.8 on 2020-07-07 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="タグ名"),
                ),
                (
                    "group",
                    models.CharField(default="", max_length=255, verbose_name="タググループ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="詳細"),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="イベント名"),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="開始時刻")),
                ("end_datetime", models.DateTimeField(verbose_name="終了時刻")),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="URL"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="画像URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="詳細"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tag", models.ManyToManyField(to="furport.Tag")),
            ],
            options={"ordering": ("start_datetime", "end_datetime")},
        ),
    ]
