# Generated by Django 3.0.8 on 2020-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tag",
            field=models.ManyToManyField(blank=True, to="furport.Tag"),
        ),
    ]
