# Generated by Django 3.0.8 on 2020-07-08 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("furport", "0002_auto_20200707_1931"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="タググループ名"
                    ),
                ),
                (
                    "color",
                    models.CharField(default="", max_length=255, verbose_name="タグ色"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="優先度")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="詳細"),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(model_name="event", name="image_url"),
        migrations.AddField(
            model_name="event",
            name="stared_by",
            field=models.ManyToManyField(
                blank=True, related_name="stared_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="twitter_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="TwitterId"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="furport.TagGroup"
            ),
        ),
    ]
