# Generated by Django 3.0.8 on 2020-07-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furport", "0004_auto_20200708_0658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="country",
            field=models.CharField(default="", max_length=255, verbose_name="国名"),
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(default="", max_length=255, verbose_name="都道府県・州名"),
        ),
    ]
