# Generated by Django 3.0.8 on 2020-07-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("furport", "0005_auto_20200708_0659"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="stared_by"),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="場所"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="詳細"),
                ),
                ("star", models.ManyToManyField(blank=True, to="furport.Event")),
            ],
            options={"ordering": ("user",)},
        ),
    ]
