# Generated by Django 3.0.8 on 2020-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furport", "0007_auto_20200709_0725"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="attend",
            field=models.ManyToManyField(
                blank=True, related_name="attend", to="furport.Event"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="star",
            field=models.ManyToManyField(
                blank=True, related_name="star", to="furport.Event"
            ),
        ),
    ]
