# Generated by Django 3.0.8 on 2020-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("furport", "0008_auto_20200709_1703")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="google_map_location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="グーグルマップ位置情報"
            ),
        )
    ]
