# Generated by Django 3.0.8 on 2020-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("furport", "0009_event_google_map_location")]

    operations = [
        migrations.RemoveField(model_name="event", name="google_map_location"),
        migrations.AddField(
            model_name="event",
            name="google_map_description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="グーグルマップ位置情報ワード"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="google_map_location_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="グーグルマップ位置情報id"
            ),
        ),
    ]
