# Generated by Django 3.0.8 on 2020-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("furport", "0011_auto_20200710_0954")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.IntegerField(blank=True, default=0, verbose_name="参加者数"),
        ),
        migrations.AddField(
            model_name="event",
            name="openness",
            field=models.IntegerField(blank=True, default=0, verbose_name="公開度"),
        ),
        migrations.AddField(
            model_name="event",
            name="search_keywords",
            field=models.TextField(blank=True, default="", verbose_name="検索キーワード"),
        ),
    ]
