# Generated by Django 3.0.8 on 2020-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furport", "0016_profile_twitter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="no_time",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="時間未定フラグ"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                blank=True, default="JST", max_length=255, verbose_name="IANAタイムゾーン名"
            ),
        ),
    ]
